import {
  AgentRuntime,
  type AgentRuntimeConfig,
  createLogger,
  LOG_CATEGORY,
  type SerializedSessionMemory,
  type Approver,
} from '@openwork/agent';
import * as fs from 'fs/promises';
import * as path from 'path';
import type { LLMGateway } from '@openwork/agent';

const log = createLogger(LOG_CATEGORY.WORKSPACE);

const OPENWORK_DIR = '.openwork';
const WORKSPACE_FILE = 'workspace.json';

/** bash 工具开关:默认启用;OPENWORK_ENABLE_BASH=0/false 时关闭(远程部署建议关闭) */
function resolveEnableBash(): boolean {
  const v = process.env.OPENWORK_ENABLE_BASH;
  if (v === undefined || v === '') return true;
  return !(v === '0' || v.toLowerCase() === 'false');
}

export interface StoredTab {
  path: string;
  cursorLine?: number;
  cursorColumn?: number;
}

/**
 * 持久化的 Agent 会话数据。
 *
 * Schema v2(2026-06 重构):用 `memory: SerializedSessionMemory` 替代旧的 `messages: SessionMessage[]`。
 * 老格式(workspace.json 含 messages 但无 memory 字段)会被安全清空——
 * 用户已确认无需迁移,只要不崩溃即可。
 */
export interface WorkspaceAgentSession {
  id: string;
  name: string;
  nameAutoGenerated: boolean;
  createdAt: number;
  lastMessageAt?: number;
  /** 会话记忆:结构化 entry 列表,含工具调用细节 */
  memory?: SerializedSessionMemory;
}

/** 工作区级别的 LLM 配置（预留接口，暂不实现功能） */
export interface WorkspaceLLMConfig {
  providerId?: string;
  model?: string;
  temperature?: number;
  maxTokens?: number;
  systemPrompt?: string;
  memoryTokenBudget?: number;
}

/** 工作区级别的 MCP 配置（预留接口，暂不实现功能） */
export interface WorkspaceMcpConfig {
  servers?: Record<string, unknown>[];
}

export interface WorkspaceData {
  workspaceId: string;
  rootPath: string;
  rootName: string;
  lightweight: boolean;
  openTabs: StoredTab[];
  activeTabPath?: string;
  createdAt: number;
  lastOpenedAt: number;
  agentSessions?: WorkspaceAgentSession[];
  llm?: WorkspaceLLMConfig;
  mcp?: WorkspaceMcpConfig;
}

interface ActiveWorkspace {
  runtime: AgentRuntime;
  data: WorkspaceData;
  config: AgentRuntimeConfig;
  lightweight: boolean;
}

export class WorkspaceManager {
  private workspaces = new Map<string, ActiveWorkspace>();
  private configDir: string;
  private approver?: Approver;

  constructor(configDir: string, approver?: Approver) {
    this.configDir = configDir;
    this.approver = approver;
  }

  async openWorkspace(rootPath: string, llmGateway: LLMGateway, lightweight = false): Promise<WorkspaceData> {
    const startMs = Date.now();
    const absRoot = path.resolve(rootPath);

    if (!lightweight) {
      let stat: { isDirectory(): boolean };
      try {
        stat = await fs.stat(absRoot);
      } catch {
        throw new Error(`Path does not exist: ${absRoot}`);
      }
      if (!stat.isDirectory()) {
        throw new Error(`Path is not a directory: ${absRoot}`);
      }
    }

    const activeProvider = llmGateway.getActiveProvider();
    const memoryTokenBudget = this.resolveMemoryTokenBudget(llmGateway);
    const config: AgentRuntimeConfig = {
      mode: 'build',
      provider: {
        apiUrl: activeProvider?.apiUrl || '',
        apiKey: activeProvider?.apiKey || '',
        model: activeProvider?.model || '',
      },
      workspaceRoot: absRoot,
      mcpServers: undefined,
      memoryTokenBudget,
      enableBash: resolveEnableBash(),
      // 权限：环境变量强制；否则 full-auto（兼容 headless）。前端建议传 auto-edit 并走 broker。
      permissionMode:
        process.env.OPENWORK_PERMISSION_MODE === 'suggest' ||
        process.env.OPENWORK_PERMISSION_MODE === 'auto-edit' ||
        process.env.OPENWORK_PERMISSION_MODE === 'full-auto'
          ? (process.env.OPENWORK_PERMISSION_MODE as 'suggest' | 'auto-edit' | 'full-auto')
          : 'full-auto',
      approver: this.approver,
    };

    const runtime = new AgentRuntime(config);

    let existingData = lightweight ? null : await this.readWorkspaceFile(absRoot);
    // 安全检查:若老 schema 含 messages 但无 memory,清空 sessions(不崩溃)
    if (existingData && this.isLegacySchema(existingData)) {
      log.warn(`Legacy workspace.json schema detected — clearing agentSessions (messages -> memory migration not supported)`, { rootPath: absRoot });
      existingData = { ...existingData, agentSessions: [] };
    }

    const workspaceId = existingData?.workspaceId || `ws_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
    const now = Date.now();

    const data: WorkspaceData = {
      workspaceId,
      rootPath: absRoot,
      rootName: path.basename(absRoot),
      lightweight,
      openTabs: existingData?.openTabs || [],
      activeTabPath: existingData?.activeTabPath,
      agentSessions: existingData?.agentSessions,
      llm: existingData?.llm,
      mcp: existingData?.mcp,
      createdAt: existingData?.createdAt || now,
      lastOpenedAt: now,
    };

    this.workspaces.set(workspaceId, { runtime, data, config, lightweight });

    // 用持久化的 memory 恢复每个 session 到 runtime
    if (data.agentSessions && data.agentSessions.length > 0) {
      for (const s of data.agentSessions) {
        if (s.memory) {
          runtime.restoreSessionMemory(s.id, s.memory);
        }
      }
    }

    if (!lightweight) {
      await this.writeWorkspaceFile(absRoot, data);
    }

    log.info(`Workspace opened: id=${workspaceId}, root="${absRoot}", lightweight=${lightweight}, ${Date.now() - startMs}ms`, { workspaceId, rootPath: absRoot, sessions: data.agentSessions?.length || 0 });
    return data;
  }

  /** 从 gateway 配置读 memoryTokenBudget(用户可在 provider 设置里配) */
  private resolveMemoryTokenBudget(llmGateway: LLMGateway): number | undefined {
    const active = llmGateway.getActiveProvider();
    // 暂时从 active provider 的 model 推断;后续可加专门的 budget 字段
    void active;
    return undefined; // 默认使用 DEFAULT_MEMORY_TOKEN_BUDGET
  }

  getRuntime(workspaceId: string): AgentRuntime | undefined {
    return this.workspaces.get(workspaceId)?.runtime;
  }

  /** 替换 workspace 的 runtime（用于从 agent 路由缓存新创建的 runtime） */
  cacheRuntime(workspaceId: string, runtime: AgentRuntime): void {
    const ws = this.workspaces.get(workspaceId);
    if (ws) {
      try { ws.runtime.dispose(); } catch { /* ignore */ }
      ws.runtime = runtime;
    }
  }

  getWorkspaceData(workspaceId: string): WorkspaceData | undefined {
    return this.workspaces.get(workspaceId)?.data;
  }

  async updateWorkspaceData(
    workspaceId: string,
    update: Partial<Pick<WorkspaceData, 'openTabs' | 'activeTabPath'>>
  ): Promise<void> {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) throw new Error(`Workspace not found: ${workspaceId}`);

    if (update.openTabs) ws.data.openTabs = update.openTabs;
    if (update.activeTabPath !== undefined) ws.data.activeTabPath = update.activeTabPath;
    ws.data.lastOpenedAt = Date.now();

    if (!ws.lightweight) {
      await this.writeWorkspaceFile(ws.data.rootPath, ws.data);
    }
  }

  /**
   * 从 runtime 拉 session memory,写入 workspace.json 的 agentSessions[].memory。
   * 在流式 done 后调用,确保最新对话已落盘。
   */
  async persistSessionMemory(workspaceId: string, sessionId: string): Promise<void> {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) throw new Error(`Workspace not found: ${workspaceId}`);

    const serialized = ws.runtime.serializeSessionMemory(sessionId);
    if (!serialized) {
      log.warn(`persistSessionMemory: no session ${sessionId} in runtime`, { workspaceId, sessionId });
      return;
    }

    if (!ws.data.agentSessions) ws.data.agentSessions = [];
    const idx = ws.data.agentSessions.findIndex(s => s.id === sessionId);
    const now = Date.now();
    if (idx !== -1) {
      ws.data.agentSessions[idx] = {
        ...ws.data.agentSessions[idx]!,
        memory: serialized,
        lastMessageAt: now,
      };
    } else {
      // 新 session:workspace.json 里没有,新建元数据
      ws.data.agentSessions.push({
        id: sessionId,
        name: '新会话',
        nameAutoGenerated: false,
        createdAt: now,
        lastMessageAt: now,
        memory: serialized,
      });
    }
    ws.data.lastOpenedAt = now;

    if (!ws.lightweight) {
      await this.writeWorkspaceFile(ws.data.rootPath, ws.data);
    }
    log.debug(`persistSessionMemory: ${serialized.entries.length} entries saved`, { workspaceId, sessionId, entries: serialized.entries.length });
  }

  /** 保存或更新 session 元数据(改名等,不影响 memory) */
  async saveAgentSession(workspaceId: string, sessionData: WorkspaceAgentSession): Promise<void> {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) throw new Error(`Workspace not found: ${workspaceId}`);

    if (!ws.data.agentSessions) ws.data.agentSessions = [];
    const idx = ws.data.agentSessions.findIndex(s => s.id === sessionData.id);
    if (idx !== -1) {
      ws.data.agentSessions[idx] = { ...ws.data.agentSessions[idx]!, ...sessionData };
    } else {
      ws.data.agentSessions.push(sessionData);
    }
    ws.data.lastOpenedAt = Date.now();

    if (!ws.lightweight) {
      await this.writeWorkspaceFile(ws.data.rootPath, ws.data);
    }
    log.debug(`Agent session saved: workspaceId=${workspaceId}, sessionId=${sessionData.id}, lightweight=${ws.lightweight}`);
  }

  /** 删除工作区下的单个 Agent 会话 */
  async deleteAgentSession(workspaceId: string, sessionId: string): Promise<void> {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) throw new Error(`Workspace not found: ${workspaceId}`);

    if (ws.data.agentSessions) {
      ws.data.agentSessions = ws.data.agentSessions.filter(s => s.id !== sessionId);
    }
    ws.runtime.deleteSession(sessionId);
    ws.data.lastOpenedAt = Date.now();

    if (!ws.lightweight) {
      await this.writeWorkspaceFile(ws.data.rootPath, ws.data);
    }
  }

  /** 获取工作区下所有 Agent 会话(元数据,不含 memory entries) */
  getAgentSessions(workspaceId: string): WorkspaceAgentSession[] {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) return [];
    return (ws.data.agentSessions || []).map(s => ({
      id: s.id,
      name: s.name,
      nameAutoGenerated: s.nameAutoGenerated,
      createdAt: s.createdAt,
      lastMessageAt: s.lastMessageAt,
    }));
  }

  /** 获取单个 session 的展示用消息(给前端 GET /messages 用) */
  getSessionDisplayMessages(workspaceId: string, sessionId: string) {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) return [];
    return ws.runtime.getSessionDisplayMessages(sessionId);
  }

  async closeWorkspace(workspaceId: string): Promise<void> {
    const ws = this.workspaces.get(workspaceId);
    if (!ws) return;

    const rootPath = ws.data.rootPath;
    if (!ws.lightweight) {
      try { await this.writeWorkspaceFile(ws.data.rootPath, ws.data); } catch { /* ignore */ }
    }
    try { await ws.runtime.dispose(); } catch { /* ignore */ }
    this.workspaces.delete(workspaceId);
    log.info(`Workspace closed: id=${workspaceId}, root="${rootPath}", lightweight=${ws.lightweight}`, { workspaceId, rootPath });
  }

  async disposeAll(): Promise<void> {
    for (const id of this.workspaces.keys()) {
      await this.closeWorkspace(id);
    }
  }

  /** 读取工作区根目录下的 .openwork/workspace.json */
  private async readWorkspaceFile(rootPath: string): Promise<WorkspaceData | null> {
    const filePath = path.join(rootPath, OPENWORK_DIR, WORKSPACE_FILE);
    try {
      const raw = await fs.readFile(filePath, 'utf-8');
      const data = JSON.parse(raw) as WorkspaceData;
      log.debug(`Workspace file read: ${filePath} (${raw.length} chars)`);
      return data;
    } catch {
      return null;
    }
  }

  /** 写入工作区配置到 .openwork/workspace.json */
  private async writeWorkspaceFile(rootPath: string, data: WorkspaceData): Promise<void> {
    const dir = path.join(rootPath, OPENWORK_DIR);
    const filePath = path.join(dir, WORKSPACE_FILE);
    try {
      const content = JSON.stringify(data, null, 2);
      await fs.mkdir(dir, { recursive: true });
      await fs.writeFile(filePath, content, 'utf-8');
      log.debug(`Workspace file written: ${filePath} (${content.length} chars)`);
    } catch (e: any) {
      log.warn(`Workspace file write failed: ${e.message}`, { filePath });
    }
  }

  /** 检测老 schema(agentSessions 含 messages 而非 memory) */
  private isLegacySchema(data: WorkspaceData): boolean {
    if (!data.agentSessions || data.agentSessions.length === 0) return false;
    const first = data.agentSessions[0]!;
    // 兼容:有任何 session 没有 memory 字段就算老(可能是从老 messages 来的)
    return !first.memory && !!(first as unknown as { messages?: unknown }).messages;
  }
}
